//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accounts
    {
        public int Id { get; set; }
        public Nullable<int> clientId { get; set; }
        public string name { get; set; }
        public Nullable<decimal> balance { get; set; }
        public Nullable<int> accountType { get; set; }
        public Nullable<int> capitalization { get; set; }
        public Nullable<int> mountCount { get; set; }
        public Nullable<int> interestRate { get; set; }
    
        public virtual Clients Clients { get; set; }
    }
}
